name = "After Dark Green"
license = "WTFPL"
licenselink = "https://github.com/ea2809/after-dark-green/blob/master/COPYING"
description = "A robust, elegant dark theme for Hugo. (Edited in green color)"
homepage = "https://comfusion.github.io/after-dark/"
tags = [
  "minimal",
  "responsive",
  "accessible",
  "terminal",
  "dark",
  "green"
]
features = [
  "Mobile-optimized",
  "SEO-optimized",
  "Responsive Design",
  "Flexbox Layouts",
  "Google Analytics",
  "Disqus",
  "Image lazyloading",
  "OpenGraph",
  "Schema Structured Data",
  "Pagination",
  "Reading time",
  "Related content",
  "Modification dating",
  "Author byline",
  "Word Count",
  "Related Posts",
  "Section Menu",
  "Block Templates",
  "Table of Contents",
  "Custom Shortcodes",
  "Keyboard Accessibility",
  "Inclusive Design",
  "Theme Variants"
]
min_version = 0.16

[author]
  name = "Josh Habdas"
  homepage = "https://habd.as"
